<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Color" Id="{94c17106-1fe3-4f89-8da2-5a9b920caf34}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Color
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Color">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>